# .streamlit/config.toml

[server]
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[runner]
magicEnabled = true
install_pip_deps = true

[logger]
level = "info"

[global]
data_directory = "/app/nltk_data"

[theme]
# This base adjusts the overall light/dark mode. "light" is needed for cream.
base = "light"
# Primary accent color (for buttons, sliders, etc.)
primaryColor = "#4CAF50" # A shade of green
# Background color for the main content area (light cream)
backgroundColor = "#FDFBF7"
# Background color for elements like sidebars (though we're removing it) or secondary containers
secondaryBackgroundColor = "#F0F2F6"
# Color of most text
textColor = "#262730"
# Font for the app
font = "sans serif" # Or "serif", "monospace"